// FoodItems.swift
import Foundation

enum Category: String, CaseIterable {
    case food = "Food"
    case animals = "Animals"
    case disney = "Disney"
    // Add more categories here
}
let foodItems: [String] = [
    "Apple", "Banana", "Orange", "Grapes", "Pineapple", "Strawberry", "Blueberry", "Raspberry", "Mango", "Peach", "Pear", "Watermelon", "Cantaloupe", "Honeydew", "Lemon", "Lime", "Cherry", "Plum", "Apricot", "Kiwi", "Blackberry", "Fig", "Date", "Papaya", "Guava", "Lychee", "Passionfruit", "Pomegranate", "Cranberry", "Mulberry", "Coconut", "Avocado", "Tomato", "Cucumber", "Bell Pepper", "Carrot", "Broccoli", "Cauliflower", "Spinach", "Lettuce", "Kale", "Swiss Chard", "Arugula", "Zucchini", "Eggplant", "Mushroom", "Onion", "Garlic", "Potato", "Sweet Potato", "Yam", "Beetroot", "Turnip", "Radish", "Peas", "Green Beans", "Asparagus", "Artichoke", "Brussel Sprouts", "Cabbage", "Celery", "Leek", "Fennel", "Okra", "Pumpkin", "Squash", "Corn", "Chili Pepper", "Jalapeño", "Habanero", "Serrano", "Poblano", "Tomato Sauce", "Ketchup", "Mayonnaise", "Mustard", "Soy Sauce", "Teriyaki Sauce", "BBQ Sauce", "Hot Sauce", "Salad Dressing", "Ranch Dressing", "Caesar Dressing", "Italian Dressing", "French Dressing", "Thousand Island Dressing", "Blue Cheese Dressing", "Vinaigrette", "Olive Oil", "Coconut Oil", "Butter", "Margarine", "Cheese", "Mozzarella", "Cheddar", "Swiss", "Gouda", "Parmesan", "Brie", "Camembert", "Feta", "Goat Cheese", "Blue Cheese", "Ricotta", "Cottage Cheese", "Cream Cheese", "Yogurt", "Milk", "Almond Milk", "Soy Milk", "Oat Milk", "Rice Milk", "Ice Cream", "Gelato", "Sorbet", "Frozen Yogurt", "Pudding", "Custard", "Whipped Cream", "Chocolate", "Dark Chocolate", "White Chocolate", "Milk Chocolate", "Candy", "Lollipop", "Gummy Bears", "Jelly Beans", "Marshmallow", "Caramel", "Toffee", "Fudge", "Peanut Butter", "Nutella", "Honey", "Maple Syrup", "Pancakes", "Waffles", "French Toast", "Cereal", "Granola", "Oatmeal", "Porridge", "Bread", "Whole Wheat Bread", "White Bread", "Sourdough", "Baguette", "Croissant", "Bagel", "Muffin", "Scone", "Biscuit", "Crackers", "Tortilla", "Pita Bread", "Naan", "Rice", "Brown Rice", "White Rice", "Basmati Rice", "Jasmine Rice", "Quinoa", "Couscous", "Barley", "Bulgur", "Pasta", "Spaghetti", "Fettuccine", "Penne", "Macaroni", "Ravioli", "Lasagna", "Gnocchi", "Dumplings", "Pizza", "Burger", "Hot Dog", "Sandwich", "Wrap", "Taco", "Burrito", "Quesadilla", "Nachos", "Fries", "Onion Rings", "Chicken Wings", "Chicken Nuggets", "Fried Chicken", "Grilled Chicken", "Roast Chicken", "Beef", "Steak", "Ribs", "Lamb", "Pork", "Bacon", "Ham", "Sausage", "Meatballs", "Fish", "Salmon", "Tuna", "Cod", "Haddock", "Mackerel", "Sardines", "Shrimp", "Crab", "Lobster", "Mussels", "Clams", "Oysters", "Scallops", "Squid", "Octopus", "Sushi", "Sashimi", "Tempura", "Ramen", "Pho", "Spring Rolls", "Egg Rolls", "Dim Sum", "Dumplings", "Pad Thai", "Fried Rice", "Stir Fry", "Curry", "Tofu", "Seitan", "Tempeh", "Falafel", "Hummus", "Guacamole", "Salsa", "Chutney", "Kimchi", "Sauerkraut", "Pickles", "Olives", "Capers", "Sun-Dried Tomatoes", "Artichoke Hearts", "Spinach Dip", "Queso Dip", "French Onion Dip", "Buffalo Chicken Dip", "Nacho Cheese Dip", "Pesto", "Alfredo Sauce", "Marinara Sauce", "Bolognese Sauce", "Carbonara Sauce", "Puttanesca Sauce", "Tzatziki Sauce", "Aioli", "Tahini", "Miso", "Wasabi", "Ginger", "Garlic Bread", "Bruschetta", "Crostini", "Pita Chips", "Bagel Chips", "Pretzels", "Popcorn", "Potato Chips", "Tortilla Chips", "Kale Chips", "Vegetable Chips", "Fruit Snacks", "Trail Mix", "Nuts", "Almonds", "Walnuts", "Cashews", "Peanuts", "Pistachios", "Pecans", "Macadamia Nuts", "Hazelnuts", "Seeds", "Sunflower Seeds", "Pumpkin Seeds", "Chia Seeds", "Flax Seeds", "Sesame Seeds", "Hemp Seeds", "Protein Bars", "Granola Bars", "Energy Bars", "Smoothies", "Juices", "Lemonade", "Iced Tea", "Hot Chocolate", "Coffee", "Espresso", "Cappuccino", "Latte", "Macchiato", "Mocha", "Americano", "Tea", "Green Tea", "Black Tea", "Herbal Tea", "Chai Tea", "Matcha", "Milkshake", "Smoothie Bowl", "Acai Bowl", "Fruit Salad", "Vegetable Salad", "Caesar Salad", "Greek Salad", "Caprese Salad", "Cobb Salad", "Chef Salad", "Chicken Salad", "Tuna Salad", "Egg Salad", "Potato Salad", "Pasta Salad", "Quinoa Salad", "Bean Salad", "Lentil Salad", "Rice Salad", "Tabbouleh", "Coleslaw", "Waldorf Salad", "Broccoli Salad", "Spinach Salad", "Kale Salad", "Avocado Salad", "Beet Salad", "Carrot Salad", "Cucumber Salad", "Tomato Salad", "Corn Salad", "Mango Salad", "Papaya Salad", "Watermelon Salad", "Strawberry Salad", "Blueberry Salad", "Raspberry Salad", "Fruit Tart", "Apple Pie", "Pumpkin Pie", "Pecan Pie", "Cherry Pie", "Blueberry Pie", "Lemon Meringue Pie", "Key Lime Pie", "Chocolate Cake", "Vanilla Cake", "Red Velvet Cake", "Carrot Cake", "Cheesecake", "Cupcakes", "Brownies", "Blondies", "Cookies", "Chocolate Chip Cookies", "Oatmeal Raisin Cookies", "Peanut Butter Cookies", "Sugar Cookies", "Gingerbread Cookies", "Biscotti", "Macarons", "Eclairs", "Profiteroles", "Cannoli", "Tiramisu", "Panna Cotta", "Creme Brulee", "Flan", "Churros", "Doughnuts", "Cinnamon Rolls", "Pastries", "Danish", "Croissants", "Strudel", "Scones", "Muffins", "Bagels", "Bread Pudding", "Rice Pudding", "Tapioca Pudding", "Custard", "Trifle", "Pavlova", "Souffle", "Ice Cream Sundae", "Milkshake", "Smoothie", "Fruit Juice", "Lemonade", "Limeade", "Iced Coffee", "Hot Chocolate", "Herbal Tea", "Green Juice", "Protein Shake", "Energy Drink", "Soda", "Sparkling Water", "Mineral Water", "Sports Drink", "Beer", "Wine", "Champagne", "Whiskey", "Vodka", "Rum", "Tequila", "Gin", "Brandy", "Sangria", "Cocktails", "Margarita"
]

let questions = [
            QuizQuestion(options: ["The cat is sleeping", "The dog is barking", "The bird is flying", "The fish is swimming"]),
            QuizQuestion(options: ["I like apples", "I like bananas", "I like grapes", "I like oranges"]),
            QuizQuestion(options: ["The car is fast", "The bike is slow", "The train is on time", "The plane is delayed"]),
            QuizQuestion(options: ["She is reading a book", "He is writing a letter", "They are watching TV", "We are playing a game"]),
            QuizQuestion(options: ["The sun is shining", "The moon is bright", "The stars are twinkling", "The clouds are fluffy"]),
            QuizQuestion(options: ["The flowers are blooming", "The trees are tall", "The grass is green", "The leaves are falling"]),
            QuizQuestion(options: ["The pizza is hot", "The ice cream is cold", "The soup is warm", "The salad is fresh"]),
            QuizQuestion(options: ["The music is loud", "The movie is interesting", "The book is thrilling", "The game is fun"]),
            QuizQuestion(options: ["The house is big", "The apartment is cozy", "The garden is beautiful", "The kitchen is clean"]),
            QuizQuestion(options: ["The ocean is deep", "The river is flowing", "The lake is calm", "The waterfall is loud"]),
            QuizQuestion(options: ["The teacher is kind", "The student is attentive", "The class is quiet", "The lesson is important"]),
            QuizQuestion(options: ["The city is busy", "The village is peaceful", "The town is growing", "The neighborhood is friendly"]),
            QuizQuestion(options: ["The shop is open", "The market is crowded", "The mall is huge", "The store is closed"]),
            QuizQuestion(options: ["The computer is new", "The phone is old", "The tablet is fast", "The laptop is slow"]),
            QuizQuestion(options: ["The cat is purring", "The dog is running", "The bird is chirping", "The fish is jumping"]),
            QuizQuestion(options: ["The clock is ticking", "The alarm is ringing", "The bell is chiming", "The watch is beeping"]),
            QuizQuestion(options: ["The doctor is helping", "The nurse is caring", "The patient is resting", "The hospital is busy"]),
            QuizQuestion(options: ["The sun is setting", "The moon is rising", "The stars are shining", "The night is calm"]),
            QuizQuestion(options: ["The child is laughing", "The baby is crying", "The parent is smiling", "The family is happy"]),
            QuizQuestion(options: ["The cake is sweet", "The chocolate is rich", "The candy is colorful", "The cookie is delicious"]),
            QuizQuestion(options: ["The bus is late", "The train is early", "The taxi is waiting", "The bike is parked"]),
            QuizQuestion(options: ["The beach is sandy", "The mountain is high", "The forest is dense", "The desert is dry"]),
            QuizQuestion(options: ["The athlete is strong", "The team is winning", "The coach is guiding", "The game is exciting"]),
            QuizQuestion(options: ["The chair is comfortable", "The table is sturdy", "The sofa is soft", "The bed is cozy"]),
            QuizQuestion(options: ["The pasta is tasty", "The rice is fluffy", "The bread is fresh", "The cheese is melted"]),
            // Add more questions as needed
        ]

let animalItems: [String] = [
    "Aardvark", "Albatross", "Alligator", "Alpaca", "Anaconda", "Ant", "Anteater", "Antelope", "Ape", "Armadillo", "Baboon", "Badger", "Bandicoot", "Barnacle", "Barracuda", "Bat", "Bear", "Beaver", "Bee", "Beetle", "Bison", "Blackbird", "Boa", "Bobcat", "Bonito", "Bonobo", "Booby", "Bovid", "Budgerigar", "Buffalo", "Butterfly", "Buzzard", "Camel", "Capybara", "Caracal", "Caribou", "Carp", "Cat", "Caterpillar", "Catfish", "Centipede", "Chameleon", "Chamois", "Cheetah", "Chicken", "Chimpanzee", "Chinchilla", "Chipmunk", "Cicada", "Clam", "Clownfish", "Cobra", "Cockroach", "Cod", "Condor", "Constrictor", "Coral", "Cougar", "Cow", "Coyote", "Crab", "Crane", "Crayfish", "Cricket", "Crocodile", "Crow", "Cuckoo", "Cuttlefish", "Deer", "Dingo", "Dodo", "Dog", "Dolphin", "Donkey", "Dormouse", "Dove", "Dragonfly", "Duck", "Dugong", "Dunlin", "Eagle", "Earthworm", "Echidna", "Eel", "Egret", "Elephant", "Elk", "Emu", "Falcon", "Ferret", "Finch", "Firefly", "Fish", "Flamingo", "Flea", "Fly", "Fox", "Frog", "Gannet", "Gazelle", "Gecko", "Gerbil", "Giraffe", "Gnat", "Gnu", "Goat", "Goldfish", "Goose", "Gorilla", "Grasshopper", "Grouse", "Guanaco", "Gull", "Hamster", "Hare", "Hawk", "Hedgehog", "Heron", "Herring", "Hippopotamus", "Hornet", "Horse", "Human", "Hummingbird", "Hyena", "Ibis", "Iguana", "Impala", "Jackal", "Jaguar", "Jellyfish", "Kangaroo", "Kingfisher", "Koala", "Kodiak", "Kookaburra", "Kouprey", "Krill", "Ladybird", "Lamprey", "Landfowl", "Lark", "Lemur", "Leopard", "Lion", "Lizard", "Llama", "Lobster", "Locust", "Loon", "Loris", "Lynx", "Macaw", "Magpie", "Mallard", "Manatee", "Mandrill", "Manta Ray", "Marmoset", "Marmot", "Meerkat", "Mink", "Mole", "Mongoose", "Monkey", "Moose", "Mosquito", "Moth", "Mouse", "Mule", "Narwhal", "Newt", "Nightingale", "Nighthawk", "Numbat", "Ocelot", "Octopus", "Okapi", "Opossum", "Orangutan", "Orca", "Ostrich", "Otter", "Owl", "Ox", "Oyster", "Panther", "Parrot", "Peacock", "Pelican", "Penguin", "Perch", "Pheasant", "Pig", "Pigeon", "Pike", "Piranha", "Platypus", "Polar Bear", "Pony", "Porcupine", "Porpoise", "Possum", "Prawn", "Puffin", "Puma", "Quail", "Rabbit", "Raccoon", "Ram", "Rat", "Raven", "Reindeer", "Rhino", "Rook", "Rooster", "Salamander", "Salmon", "Sand Dollar", "Sardine", "Scorpion", "Seahorse", "Seal", "Serval", "Shark", "Sheep", "Shrew", "Shrimp", "Skunk", "Sloth", "Snail", "Snake", "Sparrow", "Spider", "Squid", "Squirrel", "Starfish", "Stork", "Swan", "Tapir", "Tarantula", "Tarsier", "Termite", "Tiger", "Toad", "Toucan", "Trout", "Tuna", "Turkey", "Turtle", "Viper", "Vulture", "Wallaby", "Walrus", "Wasp", "Weasel", "Whale", "Wildcat", "Wildebeest", "Wolf", "Wolverine", "Wombat", "Woodpecker", "Worm", "Wren", "Yak", "Zebra", "Zebu", "Zonkey", "Zorse", "Tamarin", "Tapir", "Thrush", "Tilapia", "Titmouse", "Tortoise", "Vicuna", "Vole", "Wapiti", "Warbler", "Waxwing", "Wagtail", "Tern", "Tamarin", "Takin", "Tarantula", "Terrapin", "Tetrapod", "Thylacine", "Tiglon", "Trogon", "Troodontid", "Trumpeter", "Tropicbird", "Tuatara", "Turaco", "Uakari", "Uguisu", "Uinta Chipmunk", "Umbrellabird"
]

let disneyItems: [String] = [
    "Mickey Mouse",
    "Minnie Mouse",
    "Donald Duck",
    "Daisy Duck",
    "Goofy",
    "Pluto",
    "Cinderella",
    "Snow White",
    "Ariel",
    "Belle",
    "Jasmine",
    "Pocahontas",
    "Mulan",
    "Rapunzel",
    "Tiana",
    "Elsa",
    "Anna",
    "Moana",
    "Simba",
    "Nala",
    "Timon",
    "Pumbaa",
    "Mufasa",
    "Scar",
    "Aladdin",
    "Genie",
    "Abu",
    "Jafar",
    "Peter Pan",
    "Tinker Bell",
    "Wendy Darling",
    "Captain Hook",
    "Alice",
    "Mad Hatter",
    "Cheshire Cat",
    "Queen of Hearts",
    "Winnie the Pooh",
    "Piglet",
    "Tigger",
    "Eeyore",
    "Christopher Robin",
    "Dumbo",
    "Bambi",
    "Thumper",
    "Flower",
    "Pinocchio",
    "Jiminy Cricket",
    "Peter Pan",
    "Captain Hook",
    "Lady",
    "Tramp",
    "Baloo",
    "Bagheera",
    "Mowgli",
    "Shere Khan",
    "King Louie",
    "Hercules",
    "Megara",
    "Hades",
    "Tarzan",
    "Jane Porter",
    "Buzz Lightyear",
    "Woody",
    "Jessie",
    "Rex",
    "Mr Potato Head",
    "Hamm",
    "Bo Peep",
    "Slinky Dog",
    "Mike Wazowski",
    "Sully",
    "Boo",
    "Nemo",
    "Dory",
    "Marlin",
    "Bruce",
    "Elastigirl",
    "Mr Incredible",
    "Violet Parr",
    "Dash Parr",
    "Jack Jack Parr",
    "Edna Mode",
    "Carl Fredricksen",
    "Russell",
    "Dug",
    "WALL E",
    "EVE",
    "Lightning McQueen",
    "Mater",
    "Remy",
    "Linguini",
    "Emile",
    "Carl Fredricksen",
    "Russell",
    "Dug",
    "Joy",
    "Sadness",
    "Anger",
    "Disgust",
    "Fear",
    "Asha",
    "Hank", "Merida", "Queen Elinor",
    "King Fergus", "Angus", "Stitch", "Lilo", "Nani", "Jumba", "Pleakley",
    "Tadashi Hamada", "Hiro Hamada", "Baymax", "Honey Lemon", "Go Go Tomago",
    "Wasabi", "Fred", "Tiana", "Prince Naveen", "Dr. Facilier", "Ray", "Louis",
    "Charlotte LaBouff", "Mama Odie", "Eudora", "King Triton", "Sebastian",
    "Flounder", "Scuttle", "Prince Eric", "Grimsby", "Max", "Ursula", "Flotsam",
    "Jetsam", "Lady Tremaine", "Drizella", "Anastasia", "Fairy Godmother",
    "Gus Gus", "Jaq", "Cinderella's Prince", "Sleeping Beauty", "Aurora",
    "Prince Phillip", "Maleficent", "Flora", "Fauna", "Merryweather", "Merlin",
    "Arthur", "Maid Marian", "Robin Hood", "Little John", "Friar Tuck", "Prince John",
    "Sheriff of Nottingham", "Lady Kluck", "Roger Radcliffe", "Anita Radcliffe",
    "Pongo", "Perdita", "Cruella de Vil", "Patch", "Rolly", "Lucky",
    "Sven", "Kristoff", "Hans", "Oaken", "Olaf"
]
